### ISSUE TITLE
Temporary file is not deleted

### ISSUE THREAD

**Issue by jasom** [fukamachi/smart-buffer#1]
I'm not sure if this is intentional or not, but the temporary file (when created) is not deleted.  The user can delete the file, but that requires treating file buffers and flexistream buffers differently.  On unix-like systems you can delete an open file, so that would be an easy change, but if the intention is to also support windows, the change would be more complicated.

**Comment by fukamachi** [comment]
It may be undesirable but intended behavior.
The file will be used outside of `with-smart-buffer`, so the source file can't be deleted inside it.

**Comment by jasom** [comment]
If the file (not just the stream) is used, then there's no way around that.  I typically only use the stream, but obviously I'm not the only user of this.  Could we have some sort of finalize function that does nothing if it's in-memory and deletes the file if it's a temporary file?  Right now everywhere a smart-buffer is created the user of the smart-buffer must check if there is also a file to be deleted which is error prone.  In addition, it's unlikely to be found during testing as everything appears to be working until you run long enough to fill up `/tmp`.

**Comment by fukamachi** [comment]
It sounds fair enough to me.
I'm going to see if it can be achieved.

**Comment by fukamachi** [comment]
I added 2 functions to delete a single temporary file and all files in https://github.com/fukamachi/smart-buffer/compare/09b9a9a0b3abaa37abe9a730f5aac2643dca4e62...aa40e32a0f6bec73b1ed6835be006211a317d08f.
